const webRoutes = {
  acceptRepresentation: "/co/representatives/accept",
  address: "/address",
  aiServices: "/ai-services",
  analysis: "/analysis",
  assignRepresentative: "/co/representatives/manage",
  bio: "/bio",
  blockedUsers: "/co/blocked-users",
  blockedCompanies: "/co/blocked-companies",
  bookmarks: "/co/bookmarks",
  businessHub: "/business-hub",
  company: "/:company",
  companyEditProfile: "/:company/edit-profile",
  companyDocuments: "/company-documents",
  companyInformation: "/company-information",
  companies: "/companies",
  confirmResetPassword: "/confirm-reset-password",
  contact: "/contact",
  coNotifications: "/co/notifications",
  createCompany: "/create-company",
  dashboard: "/dashboard",
  dealRoom: "/deal-room",
  feed: "/",
  home: "/update-profile",
  login: "/login",
  logisticsHub: "/logistics-hub",
  market: "/market",
  messages: "/messages",
  messagesRoom: "/messages/:room_name",
  newsFeed: "/",
  notFound: "*",
  overview: "/overview",
  privacyPolicy: "/privacy-policy",
  productDetails: "/products/:id",
  productListing: "/products/listing",
  profile: "/profile",
  reactivateAccount: "/reactivate-account",
  representatives: "/co/representatives",
  resetPassword: "/reset-password",
  search: "/search",
  services: "/services",
  servicesAdd: "/services/add",
  servicesDetail: "/services/:id",
  settings: "/co/settings",
  signup: "/signup",
  singlePost: "/posts/:id",
  success: "/success",
  support:"/support",
  termsAndConditions: "/terms-and-conditions",
  userProfile: "/co/:userId",
  verifyAccount: "/verify-account",
  workforce: "/workforce",
};

export { webRoutes };

