const webRoutes = {
  acceptRepresentation: "/co/representatives/accept",
  address: "/address",
  analysis: "/analysis",
  assignRepresentative: "/co/representatives/manage",
  bio: "/bio",
  bookmarks: "/co/bookmarks",
  company: "/:company",
  companyEditProfile: "/:company/edit-profile",
  companyDocuments: "/company-documents",
  companyInformation: "/company-information",
  companies: "/companies",
  confirmResetPassword: "/confirm-reset-password",
  contact: "/contact",
  coNotifications: "/co/notifications",
  createCompany: "/create-company",
  feed: "/",
  home: "/update-profile",
  login: "/login",
  market: "/market",
  messages: "/messages",
  messagesRoom: "/messages/:room_name",
  newsFeed: "/",
  notFound: "*",
  overview: "/overview",
  privacyPolicy: "/privacy-policy",
  productDetails: "/products/:id",
  productListing: "/products/listing",
  profile: "/profile",
  reactivateAccount: "/reactivate-account",
  representatives: "/co/representatives",
  resetPassword: "/reset-password",
  search: "/search",
  services: "/services",
  servicesAdd: "/services/add",
  servicesDetail: "/services/:id",
  settings: "/co/settings",
  signup: "/signup",
  singlePost: "/posts/:id",
  success: "/success",
  termsAndConditions: "/terms-and-conditions",
  userProfile: "/co/:userId",
  verifyAccount: "/verify-account",
  
  // Admin Routes
  admin: "/admin",
  adminAnalytics: "/admin/analytics",
  adminUsers: "/admin/users",
  adminUsersAnalytics: "/admin/users/analytics",
  adminUsersVerification: "/admin/users/verification",
  adminCompanies: "/admin/companies",
  adminCompaniesAnalytics: "/admin/companies/analytics",
  adminCompaniesVerification: "/admin/companies/verification",
  adminCompaniesCategories: "/admin/companies/categories",
  adminProducts: "/admin/products",
  adminProductsAnalytics: "/admin/products/analytics",
  adminProductsCategories: "/admin/products/categories",
  adminProductsApproval: "/admin/products/approval",
  adminServices: "/admin/services",
  adminServicesAnalytics: "/admin/services/analytics",
  adminServicesCategories: "/admin/services/categories",
  adminServicesApproval: "/admin/services/approval",
  adminOrders: "/admin/orders",
  adminOrdersAnalytics: "/admin/orders/analytics",
  adminOrdersRevenue: "/admin/orders/revenue",
  adminPosts: "/admin/posts",
  adminPostsModeration: "/admin/posts/moderation",
  adminPostsAnalytics: "/admin/posts/analytics",
  adminMessages: "/admin/messages",
  adminMessagesAnalytics: "/admin/messages/analytics",
  adminMessagesReports: "/admin/messages/reports",
  adminNotifications: "/admin/notifications",
  adminNotificationsSend: "/admin/notifications/send",
  adminNotificationsAnalytics: "/admin/notifications/analytics",
  adminNotificationsTemplates: "/admin/notifications/templates",
  adminSettings: "/admin/settings",
  adminSettingsPlatform: "/admin/settings/platform",
  adminSettingsRoles: "/admin/settings/roles",
  adminSettingsSystem: "/admin/settings/system",
  adminSettingsApi: "/admin/settings/api",
  
  // Oil & Gas Platform Routes
  // Deal Management
  dealRooms: "/deals",
  dealRoomDetail: "/deals/:id",
  dealRoomCreate: "/deals/create",
  dealRoomEdit: "/deals/:id/edit",
  dealRoomDocuments: "/deals/:id/documents",
  dealRoomParticipants: "/deals/:id/participants",
  dealRoomMilestones: "/deals/:id/milestones",
  dealRoomActivities: "/deals/:id/activities",
  dealRoomValuations: "/deals/:id/valuations",
  dealRoomReports: "/deals/:id/reports",
  
  // Workforce Marketplace
  workforceJobs: "/jobs",
  workforceJobDetail: "/jobs/:id",
  workforceJobCreate: "/jobs/create",
  workforceJobApply: "/jobs/:id/apply",
  workforceProfiles: "/professionals",
  workforceProfileDetail: "/professionals/:id",
  workforceProfileCreate: "/professionals/create",
  workforceProfileEdit: "/professionals/edit",
  workforceEvents: "/events",
  workforceEventDetail: "/events/:id",
  workforceEventCreate: "/events/create",
  workforceApplications: "/applications",
  workforceApplicationsManage: "/applications/manage",
  workforceDashboard: "/workforce/dashboard",
  
  // AI Services
  aiDashboard: "/ai",
  aiMatching: "/ai/matching",
  aiOpportunities: "/ai/opportunities",
  aiCompliance: "/ai/compliance",
  aiAnalytics: "/ai/analytics",
  aiInsights: "/ai/insights",
  
  // Logistics Hub
  logisticsDashboard: "/logistics",
  logisticsShipments: "/logistics/shipments",
  logisticsShipmentDetail: "/logistics/shipments/:id",
  logisticsShipmentCreate: "/logistics/shipments/create",
  logisticsInventory: "/logistics/inventory",
  logisticsInventoryDetail: "/logistics/inventory/:id",
  logisticsSuppliers: "/logistics/suppliers",
  logisticsSupplierDetail: "/logistics/suppliers/:id",
  logisticsTracking: "/logistics/tracking",
  
  // Trust & Verification
  trustDashboard: "/trust",
  trustVerification: "/trust/verification",
  trustVerificationStatus: "/trust/verification/:id",
  trustReputation: "/trust/reputation",
  trustReputationUser: "/trust/reputation/:userId",
  trustRatings: "/trust/ratings",
  trustReviews: "/trust/reviews",
  
  // Specialized Tools
  toolsDashboard: "/tools",
  toolsEquipment: "/tools/equipment",
  toolsEquipmentDetail: "/tools/equipment/:id",
  toolsEquipmentRental: "/tools/equipment/rental",
  toolsHSE: "/tools/hse",
  toolsHSEIncidents: "/tools/hse/incidents",
  toolsHSECompliance: "/tools/hse/compliance",
  toolsHSEInspections: "/tools/hse/inspections",
  toolsSupplyChain: "/tools/supply-chain",
  toolsSupplyChainOptimization: "/tools/supply-chain/optimization",
  toolsRegulatory: "/tools/regulatory",
  toolsRegulatoryCompliance: "/tools/regulatory/compliance",
  toolsWorkflow: "/tools/workflow",
  toolsWorkflowManagement: "/tools/workflow/management",
  
  // Dashboard & Overview
  platformDashboard: "/dashboard",
  platformOverview: "/overview",
  platformAnalytics: "/analytics",
  platformReports: "/reports",
  
  // User Management
  userProfile: "/user/profile",
  userSettings: "/user/settings",
  userNotifications: "/user/notifications",
  userSubscription: "/user/subscription",
  
  // Company Management  
  companyDashboard: "/company/dashboard",
  companyProfile: "/company/profile",
  companyTeam: "/company/team",
  companyVerification: "/company/verification",
  companyBilling: "/company/billing",
};

export { webRoutes };

