const webRoutes = {
  acceptRepresentation: "/co/representatives/accept",
  address: "/address",
  analysis: "/analysis",
  assignRepresentative: "/co/representatives/manage",
  bio: "/bio",
  bookmarks: "/co/bookmarks",
  company: "/:company",
  companyEditProfile: "/:company/edit-profile",
  companyDocuments: "/company-documents",
  companyInformation: "/company-information",
  companies: "/companies",
  confirmResetPassword: "/confirm-reset-password",
  contact: "/contact",
  coNotifications: "/co/notifications",
  createCompany: "/create-company",
  feed: "/",
  home: "/update-profile",
  login: "/login",
  market: "/market",
  messages: "/messages",
  messagesRoom: "/messages/:room_name",
  newsFeed: "/",
  notFound: "*",
  overview: "/overview",
  privacyPolicy: "/privacy-policy",
  productDetails: "/products/:id",
  productListing: "/products/listing",
  profile: "/profile",
  reactivateAccount: "/reactivate-account",
  representatives: "/co/representatives",
  resetPassword: "/reset-password",
  search: "/search",
  services: "/services",
  servicesAdd: "/services/add",
  servicesDetail: "/services/:id",
  settings: "/co/settings",
  signup: "/signup",
  singlePost: "/posts/:id",
  success: "/success",
  termsAndConditions: "/terms-and-conditions",
  userProfile: "/co/:userId",
  verifyAccount: "/verify-account",
  
  // Admin Routes
  admin: "/admin",
  adminAnalytics: "/admin/analytics",
  adminUsers: "/admin/users",
  adminUsersAnalytics: "/admin/users/analytics",
  adminUsersVerification: "/admin/users/verification",
  adminCompanies: "/admin/companies",
  adminCompaniesAnalytics: "/admin/companies/analytics",
  adminCompaniesVerification: "/admin/companies/verification",
  adminCompaniesCategories: "/admin/companies/categories",
  adminProducts: "/admin/products",
  adminProductsAnalytics: "/admin/products/analytics",
  adminProductsCategories: "/admin/products/categories",
  adminProductsApproval: "/admin/products/approval",
  adminServices: "/admin/services",
  adminServicesAnalytics: "/admin/services/analytics",
  adminServicesCategories: "/admin/services/categories",
  adminServicesApproval: "/admin/services/approval",
  adminOrders: "/admin/orders",
  adminOrdersAnalytics: "/admin/orders/analytics",
  adminOrdersRevenue: "/admin/orders/revenue",
  adminPosts: "/admin/posts",
  adminPostsModeration: "/admin/posts/moderation",
  adminPostsAnalytics: "/admin/posts/analytics",
  adminMessages: "/admin/messages",
  adminMessagesAnalytics: "/admin/messages/analytics",
  adminMessagesReports: "/admin/messages/reports",
  adminNotifications: "/admin/notifications",
  adminNotificationsSend: "/admin/notifications/send",
  adminNotificationsAnalytics: "/admin/notifications/analytics",
  adminNotificationsTemplates: "/admin/notifications/templates",
  adminSettings: "/admin/settings",
  adminSettingsPlatform: "/admin/settings/platform",
  adminSettingsRoles: "/admin/settings/roles",
  adminSettingsSystem: "/admin/settings/system",
  adminSettingsApi: "/admin/settings/api",
  
  // Oil & Gas Platform Routes
  // Deal Management
  dealRooms: "/deals",
  myParticipations: "/deals/my-participations",
  dealRoomDetail: "/deals/:id",
  dealRoomCreate: "/deals/create",
  dealRoomEdit: "/deals/:id/edit",
  dealRoomDocuments: "/deals/:id/documents",
  dealRoomParticipants: "/deals/:id/participants",
  dealRoomMilestones: "/deals/:id/milestones",
  dealRoomActivities: "/deals/:id/activities",
  dealRoomValuations: "/deals/:id/valuations",
  dealRoomReports: "/deals/:id/reports",
  
  // Workforce Marketplace
  workforceJobs: "/jobs",
  workforceJobDetail: "/jobs/:id",
  workforceJobCreate: "/jobs/create",
  workforceJobApply: "/jobs/:id/apply",
  workforceMyPostedJobs: "/jobs/my-posted",
  workforceProfiles: "/professionals",
  workforceProfileDetail: "/professionals/:id",
  workforceProfileCreate: "/professionals/create",
  workforceProfileEdit: "/professionals/:id/edit",
  workforceEvents: "/events",
  workforceEventDetail: "/events/:id",
  workforceEventCreate: "/events/create",
  workforceEventEdit: "/events/:id/edit",
  workforceMyEvents: "/events/my-events",
  workforceMyRegistrations: "/events/my-registrations",
  workforceApplications: "/applications",
  workforceApplicationsManage: "/applications/manage",
  workforceDashboard: "/workforce/dashboard",
  
  // AI Services
  aiDashboard: "/ai",
  aiMatching: "/ai/matching",
  aiOpportunities: "/ai/opportunities",
  aiCompliance: "/ai/compliance",
  aiAnalytics: "/ai/analytics",
  aiInsights: "/ai/insights",
  
  // Logistics Hub
  logistics: "/logistics",
  logisticsDashboard: "/logistics",
  logisticsRequests: "/logistics/requests",
  logisticsRequestDetail: "/logistics/requests/:id",
  logisticsRequestCreate: "/logistics/requests/create",
  logisticsRequestEdit: "/logistics/requests/:id/edit",
  logisticsShipments: "/logistics/shipments",
  logisticsShipmentDetail: "/logistics/shipments/:id",
  logisticsShipmentCreate: "/logistics/shipments/create",
  logisticsShipmentEdit: "/logistics/shipments/:id/edit",
  logisticsInventory: "/logistics/inventory",
  logisticsInventoryDetail: "/logistics/inventory/:id",
  logisticsInventoryCreate: "/logistics/inventory/create",
  logisticsInventoryEdit: "/logistics/inventory/:id/edit",
  logisticsTracking: "/logistics/tracking",
  
  // Inventory Management
  inventoryDashboard: "/inventory",
  inventoryItems: "/inventory/items",
  inventoryItemDetail: "/inventory/items/:id",
  inventoryItemCreate: "/inventory/items/create",
  inventoryItemEdit: "/inventory/items/:id/edit",
  inventoryWarehouses: "/inventory/warehouses",
  inventoryWarehouseDetail: "/inventory/warehouses/:id",
  inventoryWarehouseCreate: "/inventory/warehouses/create",
  inventoryWarehouseEdit: "/inventory/warehouses/:id/edit",
  inventoryCategories: "/inventory/categories",
  inventoryTransactions: "/inventory/transactions",
  inventoryAlerts: "/inventory/alerts",
  inventoryReports: "/inventory/reports",
  inventoryReportCreate: "/inventory/reports/create",
  inventoryReportDetail: "/inventory/reports/:id",
  
  // Knowledge Hub
  knowledgeHub: "/knowledge",
  knowledgeArticles: "/knowledge/articles",
  knowledgeArticleDetail: "/knowledge/articles/:slug",
  knowledgeArticleCreate: "/knowledge/articles/create",
  knowledgeArticleEdit: "/knowledge/articles/:slug/edit",
  knowledgeForums: "/knowledge/forums",
  knowledgeForumCreate: "/knowledge/forums/create",
  knowledgeForumDetail: "/knowledge/forums/:slug",
  knowledgeTopics: "/knowledge/topics",
  knowledgeForumTopicDetail: "/knowledge/topics/:slug",
  knowledgeForumTopicCreate: "/knowledge/forums/:forumSlug/topics/create",
  knowledgeForumTopicEdit: "/knowledge/topics/:slug/edit",
  knowledgeCategories: "/knowledge/categories",
  knowledgeCategoryDetail: "/knowledge/categories/:slug",
  knowledgeTags: "/knowledge/tags",
  knowledgeTagDetail: "/knowledge/tags/:slug",
  knowledgeModeration: "/knowledge/moderation",
  knowledgeSearch: "/knowledge/search",
  
  // Dashboard & Overview
  platformDashboard: "/dashboard",
  platformOverview: "/overview",
  platformAnalytics: "/analytics",
  
  // Featured Ads
  featuredAds: "/ads",
  
  // User Management
  userProfile: "/user/profile",
  userSettings: "/user/settings",
  userNotifications: "/user/notifications",
  userSubscription: "/user/subscription",
  
  // Subscriptions
  subscriptions: "/subscriptions",
  subscriptionDashboard: "/subscriptions/dashboard",
  subscriptionPlanDetail: "/subscriptions/plans/:planId",
  subscriptionPlanCompare: "/subscriptions/compare",
  subscriptionUpgrade: "/subscriptions/upgrade/:planId",
  subscriptionManagement: "/subscriptions/management",
  subscriptionFeatures: "/subscriptions/features",
  subscriptionBilling: "/subscriptions/billing",
  
  // Enterprise Suite Routes
  enterprise: "/enterprise",
  enterpriseDashboard: "/enterprise",
  enterpriseSubscriptions: "/enterprise/subscriptions", 
  enterpriseAdvertising: "/enterprise/advertising",
  enterpriseAnalytics: "/enterprise/analytics",
  
  // Company Management  
  companyDashboard: "/company/dashboard",
  companyProfile: "/company/profile",
  companyTeam: "/company/team",
  companyVerification: "/company/verification",
  companyBilling: "/company/billing",
};

export { webRoutes };

