function getRandomOilAndGasKeyword() {
  const keywords = [
    // Upstream
    "exploration",
    "drilling",
    "offshore drilling",
    "onshore drilling",
    "well logging",
    "seismic survey",
    "geophysics",
    "mud logging",
    "reservoir engineering",
    "completion",
    "perforation",
    "subsurface",
    "production engineering",
    // Midstream
    "pipeline",
    "LNG",
    "natural gas",
    "gas processing",
    "crude oil transportation",
    "compressor station",
    "storage tank",
    "pipeline inspection",
    "midstream infrastructure",
    "FPSO",
    "flare gas",
    // Downstream
    "refinery",
    "petrochemical",
    "fuel distribution",
    "lubricants",
    "gas station",
    "downstream marketing",
    "bitumen",
    "hydrocracking",
    "distillation",
    "catalytic reforming",
    // Equipment & Services
    "rig equipment",
    "blowout preventer",
    "drill bit",
    "mud pump",
    "rotary table",
    "subsea tree",
    "wireline services",
    "logging while drilling",
    "measurement while drilling",
    "wellhead equipment",
    // Safety & Standards
    "HSE",
    "safety inspection",
    "ISO 14001",
    "emergency response",
    "environmental audit",
    "fire suppression",
    "spill management",
    "PPE",
    "compliance audit",
    "OSHA",
    "NEBOSH",
    // Commodities & Trading
    "Brent crude",
    "WTI",
    "oil price",
    "futures contract",
    "commodities trading",
    "hedging",
    "barrel of oil",
    // Business & Markets
    "local content",
    "oil revenue",
    "NOC",
    "IOC",
    "upstream investment",
    "block license",
    "joint venture",
    "oil field services",
    "contractor",
    "tendering",
    "marginal fields",
    "indigenous operator",
    // Renewables & Transition
    "energy transition",
    "carbon capture",
    "CCUS",
    "green hydrogen",
    "gas-to-power",
    "clean energy",
    // Nigerian/African Context (custom)
    "NNPC",
    "NAPIMS",
    "DPR",
    "NUPRC",
    "NOGICD",
    "AKK pipeline",
    "NLNG",
    "Niger Delta",
    "host community",
    "pipeline vandalism",
    "artisanal refining",
    "local fabrication",
    // Career & Training
    "petroleum engineering",
    "geoscience",
    "offshore certification",
    "welding",
    "subsea training",
    "rig operation",
    "ROV pilot",
    "oil and gas internship",
    "industry certification",
    // Digital & Innovation
    "digital oilfield",
    "AI in energy",
    "data logging",
    "SCADA",
    "GIS mapping",
    "remote monitoring",
    "industrial IoT",
    "predictive maintenance",
    "automation in drilling",
  ];

  const index = Math.floor(Math.random() * keywords.length);
  return keywords[index];
}
