// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/posts/:id": {
    params: {
      "id": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/address": {
    params: {};
  };
  "/bio": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/update-profile": {
    params: {};
  };
  "/overview": {
    params: {};
  };
  "/create-company": {
    params: {};
  };
  "/company-documents": {
    params: {};
  };
  "/company-information": {
    params: {};
  };
  "/analysis": {
    params: {};
  };
  "/co/blocked-users": {
    params: {};
  };
  "/co/blocked-companies": {
    params: {};
  };
  "/co/bookmarks": {
    params: {};
  };
  "/business-hub": {
    params: {};
  };
  "/companies": {
    params: {};
  };
  "/co/notifications": {
    params: {};
  };
  "/:company": {
    params: {
      "company": string;
    };
  };
  "/:company/edit-profile": {
    params: {
      "company": string;
    };
  };
  "/market": {
    params: {};
  };
  "/messages": {
    params: {};
  };
  "/products/:id": {
    params: {
      "id": string;
    };
  };
  "/products/listing": {
    params: {};
  };
  "/co/representatives": {
    params: {};
  };
  "/co/representatives/manage": {
    params: {};
  };
  "/co/representatives/accept": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/services/add": {
    params: {};
  };
  "/services/:id": {
    params: {
      "id": string;
    };
  };
  "/co/settings": {
    params: {};
  };
  "/co/:userId": {
    params: {
      "userId": string;
    };
  };
  "/support": {
    params: {};
  };
  "/deal-room": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/reactivate-account": {
    params: {};
  };
  "/verify-account": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/confirm-reset-password": {
    params: {};
  };
  "/success": {
    params: {};
  };
  "/terms-and-conditions": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/posts/:id" | "/profile" | "/address" | "/bio" | "/contact" | "/update-profile" | "/overview" | "/create-company" | "/company-documents" | "/company-information" | "/analysis" | "/co/blocked-users" | "/co/blocked-companies" | "/co/bookmarks" | "/business-hub" | "/companies" | "/co/notifications" | "/:company" | "/:company/edit-profile" | "/market" | "/messages" | "/products/:id" | "/products/listing" | "/co/representatives" | "/co/representatives/manage" | "/co/representatives/accept" | "/search" | "/services" | "/services/add" | "/services/:id" | "/co/settings" | "/co/:userId" | "/support" | "/deal-room" | "/signup" | "/login" | "/reactivate-account" | "/verify-account" | "/reset-password" | "/confirm-reset-password" | "/success" | "/terms-and-conditions" | "/privacy-policy";
  };
  "../pages/AppLayout.jsx": {
    id: "../pages/AppLayout";
    page: "/" | "/posts/:id" | "/profile" | "/address" | "/bio" | "/contact" | "/update-profile" | "/overview" | "/create-company" | "/company-documents" | "/company-information" | "/analysis" | "/co/blocked-users" | "/co/blocked-companies" | "/co/bookmarks" | "/companies" | "/co/notifications" | "/:company" | "/:company/edit-profile" | "/market" | "/messages" | "/products/:id" | "/products/listing" | "/co/representatives" | "/co/representatives/manage" | "/co/representatives/accept" | "/search" | "/services" | "/services/add" | "/services/:id" | "/co/settings" | "/co/:userId" | "/support";
  };
  "../pages/FeedLayout.jsx": {
    id: "../pages/FeedLayout";
    page: "/" | "/posts/:id";
  };
  "../pages/feed/newsFeed.jsx": {
    id: "../pages/feed/newsFeed";
    page: "/";
  };
  "../pages/posts/singlePostPage.jsx": {
    id: "../pages/posts/singlePostPage";
    page: "/posts/:id";
  };
  "../components/profile/profile.jsx": {
    id: "../components/profile/profile";
    page: "/profile";
  };
  "../components/profile/layout.jsx": {
    id: "../components/profile/layout";
    page: "/address" | "/bio" | "/contact" | "/update-profile" | "/overview";
  };
  "../components/profile/address.jsx": {
    id: "../components/profile/address";
    page: "/address";
  };
  "../components/profile/bio.jsx": {
    id: "../components/profile/bio";
    page: "/bio";
  };
  "../components/profile/contact.jsx": {
    id: "../components/profile/contact";
    page: "/contact";
  };
  "../components/profile/home.jsx": {
    id: "../components/profile/home";
    page: "/update-profile";
  };
  "../components/profile/overview.jsx": {
    id: "../components/profile/overview";
    page: "/overview";
  };
  "../pages/company/layout.jsx": {
    id: "../pages/company/layout";
    page: "/create-company" | "/company-documents" | "/company-information";
  };
  "../pages/company/index.jsx": {
    id: "../pages/company/index";
    page: "/create-company";
  };
  "../pages/company/CompanyDocuments.jsx": {
    id: "../pages/company/CompanyDocuments";
    page: "/company-documents";
  };
  "../pages/company/CompanyInformation.jsx": {
    id: "../pages/company/CompanyInformation";
    page: "/company-information";
  };
  "../pages/market/analysis.jsx": {
    id: "../pages/market/analysis";
    page: "/analysis";
  };
  "../pages/blocked-users/index.jsx": {
    id: "../pages/blocked-users/index";
    page: "/co/blocked-users";
  };
  "../pages/blocked-companies/index.jsx": {
    id: "../pages/blocked-companies/index";
    page: "/co/blocked-companies";
  };
  "../pages/bookmark/index.jsx": {
    id: "../pages/bookmark/index";
    page: "/co/bookmarks";
  };
  "../pages/businesshub/BusinessHub.jsx": {
    id: "../pages/businesshub/BusinessHub";
    page: "/business-hub";
  };
  "../pages/companies/index.jsx": {
    id: "../pages/companies/index";
    page: "/companies";
  };
  "../components/notifications.jsx": {
    id: "../components/notifications";
    page: "/co/notifications";
  };
  "../pages/feed/companyProfile.jsx": {
    id: "../pages/feed/companyProfile";
    page: "/:company";
  };
  "../pages/company/edit/index.jsx": {
    id: "../pages/company/edit/index";
    page: "/:company/edit-profile";
  };
  "../pages/market/market.jsx": {
    id: "../pages/market/market";
    page: "/market";
  };
  "../pages/messages/layout.jsx": {
    id: "../pages/messages/layout";
    page: "/messages";
  };
  "../pages/market/product.jsx": {
    id: "../pages/market/product";
    page: "/products/:id";
  };
  "../pages/market/listing.jsx": {
    id: "../pages/market/listing";
    page: "/products/listing";
  };
  "../pages/representatives/index.jsx": {
    id: "../pages/representatives/index";
    page: "/co/representatives";
  };
  "../pages/representatives/AssignRepresentative.jsx": {
    id: "../pages/representatives/AssignRepresentative";
    page: "/co/representatives/manage";
  };
  "../pages/representatives/AcceptRepresentation.jsx": {
    id: "../pages/representatives/AcceptRepresentation";
    page: "/co/representatives/accept";
  };
  "../pages/search/index.jsx": {
    id: "../pages/search/index";
    page: "/search";
  };
  "../pages/service/service.jsx": {
    id: "../pages/service/service";
    page: "/services";
  };
  "../pages/service/serviceAdmin.jsx": {
    id: "../pages/service/serviceAdmin";
    page: "/services/add";
  };
  "../pages/service/serviceOverview.jsx": {
    id: "../pages/service/serviceOverview";
    page: "/services/:id";
  };
  "../pages/settings/index.jsx": {
    id: "../pages/settings/index";
    page: "/co/settings";
  };
  "../pages/feed/userProfile.jsx": {
    id: "../pages/feed/userProfile";
    page: "/co/:userId";
  };
  "../pages/support/Support.jsx": {
    id: "../pages/support/Support";
    page: "/support";
  };
  "../pages/dealRoom/dealRoom.jsx": {
    id: "../pages/dealRoom/dealRoom";
    page: "/deal-room";
  };
  "../pages/authentication/AuthLayout.jsx": {
    id: "../pages/authentication/AuthLayout";
    page: "/signup" | "/login" | "/reactivate-account" | "/verify-account" | "/reset-password" | "/confirm-reset-password" | "/success";
  };
  "../pages/authentication/signup.jsx": {
    id: "../pages/authentication/signup";
    page: "/signup";
  };
  "../pages/authentication/login.jsx": {
    id: "../pages/authentication/login";
    page: "/login";
  };
  "../pages/authentication/reactivation.jsx": {
    id: "../pages/authentication/reactivation";
    page: "/reactivate-account";
  };
  "../pages/authentication/verify-account.jsx": {
    id: "../pages/authentication/verify-account";
    page: "/verify-account";
  };
  "../pages/authentication/reset-password.jsx": {
    id: "../pages/authentication/reset-password";
    page: "/reset-password";
  };
  "../pages/authentication/confirmPasswordReset.jsx": {
    id: "../pages/authentication/confirmPasswordReset";
    page: "/confirm-reset-password";
  };
  "../pages/authentication/successpage.jsx": {
    id: "../pages/authentication/successpage";
    page: "/success";
  };
  "../pages/terms&policies/termsLayout.jsx": {
    id: "../pages/terms&policies/termsLayout";
    page: "/terms-and-conditions" | "/privacy-policy";
  };
  "../pages/terms&policies/terms.jsx": {
    id: "../pages/terms&policies/terms";
    page: "/terms-and-conditions";
  };
  "../pages/terms&policies/policy.jsx": {
    id: "../pages/terms&policies/policy";
    page: "/privacy-policy";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.jsx");
  "../pages/AppLayout": typeof import("./src/app/../pages/AppLayout.jsx");
  "../pages/FeedLayout": typeof import("./src/app/../pages/FeedLayout.jsx");
  "../pages/feed/newsFeed": typeof import("./src/app/../pages/feed/newsFeed.jsx");
  "../pages/posts/singlePostPage": typeof import("./src/app/../pages/posts/singlePostPage.jsx");
  "../components/profile/profile": typeof import("./src/app/../components/profile/profile.jsx");
  "../components/profile/layout": typeof import("./src/app/../components/profile/layout.jsx");
  "../components/profile/address": typeof import("./src/app/../components/profile/address.jsx");
  "../components/profile/bio": typeof import("./src/app/../components/profile/bio.jsx");
  "../components/profile/contact": typeof import("./src/app/../components/profile/contact.jsx");
  "../components/profile/home": typeof import("./src/app/../components/profile/home.jsx");
  "../components/profile/overview": typeof import("./src/app/../components/profile/overview.jsx");
  "../pages/company/layout": typeof import("./src/app/../pages/company/layout.jsx");
  "../pages/company/index": typeof import("./src/app/../pages/company/index.jsx");
  "../pages/company/CompanyDocuments": typeof import("./src/app/../pages/company/CompanyDocuments.jsx");
  "../pages/company/CompanyInformation": typeof import("./src/app/../pages/company/CompanyInformation.jsx");
  "../pages/market/analysis": typeof import("./src/app/../pages/market/analysis.jsx");
  "../pages/blocked-users/index": typeof import("./src/app/../pages/blocked-users/index.jsx");
  "../pages/blocked-companies/index": typeof import("./src/app/../pages/blocked-companies/index.jsx");
  "../pages/bookmark/index": typeof import("./src/app/../pages/bookmark/index.jsx");
  "../pages/companies/index": typeof import("./src/app/../pages/companies/index.jsx");
  "../components/notifications": typeof import("./src/app/../components/notifications.jsx");
  "../pages/feed/companyProfile": typeof import("./src/app/../pages/feed/companyProfile.jsx");
  "../pages/company/edit/index": typeof import("./src/app/../pages/company/edit/index.jsx");
  "../pages/market/market": typeof import("./src/app/../pages/market/market.jsx");
  "../pages/messages/layout": typeof import("./src/app/../pages/messages/layout.jsx");
  "../pages/market/product": typeof import("./src/app/../pages/market/product.jsx");
  "../pages/market/listing": typeof import("./src/app/../pages/market/listing.jsx");
  "../pages/representatives/index": typeof import("./src/app/../pages/representatives/index.jsx");
  "../pages/representatives/AssignRepresentative": typeof import("./src/app/../pages/representatives/AssignRepresentative.jsx");
  "../pages/representatives/AcceptRepresentation": typeof import("./src/app/../pages/representatives/AcceptRepresentation.jsx");
  "../pages/search/index": typeof import("./src/app/../pages/search/index.jsx");
  "../pages/service/service": typeof import("./src/app/../pages/service/service.jsx");
  "../pages/service/serviceAdmin": typeof import("./src/app/../pages/service/serviceAdmin.jsx");
  "../pages/service/serviceOverview": typeof import("./src/app/../pages/service/serviceOverview.jsx");
  "../pages/settings/index": typeof import("./src/app/../pages/settings/index.jsx");
  "../pages/feed/userProfile": typeof import("./src/app/../pages/feed/userProfile.jsx");
  "../pages/support/Support": typeof import("./src/app/../pages/support/Support.jsx");
  "../pages/dealRoom/dealRoom": typeof import("./src/app/../pages/dealRoom/dealRoom.jsx");
  "../pages/authentication/AuthLayout": typeof import("./src/app/../pages/authentication/AuthLayout.jsx");
  "../pages/authentication/signup": typeof import("./src/app/../pages/authentication/signup.jsx");
  "../pages/authentication/login": typeof import("./src/app/../pages/authentication/login.jsx");
  "../pages/authentication/reactivation": typeof import("./src/app/../pages/authentication/reactivation.jsx");
  "../pages/authentication/verify-account": typeof import("./src/app/../pages/authentication/verify-account.jsx");
  "../pages/authentication/reset-password": typeof import("./src/app/../pages/authentication/reset-password.jsx");
  "../pages/authentication/confirmPasswordReset": typeof import("./src/app/../pages/authentication/confirmPasswordReset.jsx");
  "../pages/authentication/successpage": typeof import("./src/app/../pages/authentication/successpage.jsx");
  "../pages/terms&policies/termsLayout": typeof import("./src/app/../pages/terms&policies/termsLayout.jsx");
  "../pages/terms&policies/terms": typeof import("./src/app/../pages/terms&policies/terms.jsx");
  "../pages/terms&policies/policy": typeof import("./src/app/../pages/terms&policies/policy.jsx");
};