// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/posts/:id": {
    params: {
      "id": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/address": {
    params: {};
  };
  "/bio": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/update-profile": {
    params: {};
  };
  "/overview": {
    params: {};
  };
  "/create-company": {
    params: {};
  };
  "/company-documents": {
    params: {};
  };
  "/company-information": {
    params: {};
  };
  "/analysis": {
    params: {};
  };
  "/co/bookmarks": {
    params: {};
  };
  "/companies": {
    params: {};
  };
  "/co/notifications": {
    params: {};
  };
  "/:company": {
    params: {
      "company": string;
    };
  };
  "/:company/edit-profile": {
    params: {
      "company": string;
    };
  };
  "/market": {
    params: {};
  };
  "/messages": {
    params: {};
  };
  "/products/:id": {
    params: {
      "id": string;
    };
  };
  "/products/listing": {
    params: {};
  };
  "/co/representatives": {
    params: {};
  };
  "/co/representatives/manage": {
    params: {};
  };
  "/co/representatives/accept": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/services/add": {
    params: {};
  };
  "/services/:id": {
    params: {
      "id": string;
    };
  };
  "/co/settings": {
    params: {};
  };
  "/co/:userId": {
    params: {
      "userId": string;
    };
  };
  "/signup": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/reactivate-account": {
    params: {};
  };
  "/verify-account": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/confirm-reset-password": {
    params: {};
  };
  "/success": {
    params: {};
  };
  "/terms-and-conditions": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/posts/:id" | "/profile" | "/address" | "/bio" | "/contact" | "/update-profile" | "/overview" | "/create-company" | "/company-documents" | "/company-information" | "/analysis" | "/co/bookmarks" | "/companies" | "/co/notifications" | "/:company" | "/:company/edit-profile" | "/market" | "/messages" | "/products/:id" | "/products/listing" | "/co/representatives" | "/co/representatives/manage" | "/co/representatives/accept" | "/search" | "/services" | "/services/add" | "/services/:id" | "/co/settings" | "/co/:userId" | "/signup" | "/login" | "/reactivate-account" | "/verify-account" | "/reset-password" | "/confirm-reset-password" | "/success" | "/terms-and-conditions" | "/privacy-policy";
  };
  "../pages/AppLayout.jsx": {
    id: "../pages/AppLayout";
    page: "/" | "/posts/:id" | "/profile" | "/address" | "/bio" | "/contact" | "/update-profile" | "/overview" | "/create-company" | "/company-documents" | "/company-information" | "/analysis" | "/co/bookmarks" | "/companies" | "/co/notifications" | "/:company" | "/:company/edit-profile" | "/market" | "/messages" | "/products/:id" | "/products/listing" | "/co/representatives" | "/co/representatives/manage" | "/co/representatives/accept" | "/search" | "/services" | "/services/add" | "/services/:id" | "/co/settings" | "/co/:userId";
  };
  "../pages/FeedLayout.jsx": {
    id: "../pages/FeedLayout";
    page: "/" | "/posts/:id";
  };
  "../pages/feed/newsFeed.jsx": {
    id: "../pages/feed/newsFeed";
    page: "/";
  };
  "../pages/posts/singlePostPage.jsx": {
    id: "../pages/posts/singlePostPage";
    page: "/posts/:id";
  };
  "../components/profile/profile.jsx": {
    id: "../components/profile/profile";
    page: "/profile";
  };
  "../components/profile/layout.jsx": {
    id: "../components/profile/layout";
    page: "/address" | "/bio" | "/contact" | "/update-profile" | "/overview";
  };
  "../components/profile/address.jsx": {
    id: "../components/profile/address";
    page: "/address";
  };
  "../components/profile/bio.jsx": {
    id: "../components/profile/bio";
    page: "/bio";
  };
  "../components/profile/contact.jsx": {
    id: "../components/profile/contact";
    page: "/contact";
  };
  "../components/profile/home.jsx": {
    id: "../components/profile/home";
    page: "/update-profile";
  };
  "../components/profile/overview.jsx": {
    id: "../components/profile/overview";
    page: "/overview";
  };
  "../pages/company/layout.jsx": {
    id: "../pages/company/layout";
    page: "/create-company" | "/company-documents" | "/company-information";
  };
  "../pages/company/index.jsx": {
    id: "../pages/company/index";
    page: "/create-company";
  };
  "../pages/company/CompanyDocuments.jsx": {
    id: "../pages/company/CompanyDocuments";
    page: "/company-documents";
  };
  "../pages/company/CompanyInformation.jsx": {
    id: "../pages/company/CompanyInformation";
    page: "/company-information";
  };
  "../pages/market/analysis.jsx": {
    id: "../pages/market/analysis";
    page: "/analysis";
  };
  "../pages/bookmark/index.jsx": {
    id: "../pages/bookmark/index";
    page: "/co/bookmarks";
  };
  "../pages/companies/index.jsx": {
    id: "../pages/companies/index";
    page: "/companies";
  };
  "../components/notifications.jsx": {
    id: "../components/notifications";
    page: "/co/notifications";
  };
  "../pages/feed/companyProfile.jsx": {
    id: "../pages/feed/companyProfile";
    page: "/:company";
  };
  "../pages/company/edit/index.jsx": {
    id: "../pages/company/edit/index";
    page: "/:company/edit-profile";
  };
  "../pages/market/market.jsx": {
    id: "../pages/market/market";
    page: "/market";
  };
  "../pages/messages/layout.jsx": {
    id: "../pages/messages/layout";
    page: "/messages";
  };
  "../pages/market/product.jsx": {
    id: "../pages/market/product";
    page: "/products/:id";
  };
  "../pages/market/listing.jsx": {
    id: "../pages/market/listing";
    page: "/products/listing";
  };
  "../pages/representatives/index.jsx": {
    id: "../pages/representatives/index";
    page: "/co/representatives";
  };
  "../pages/representatives/AssignRepresentative.jsx": {
    id: "../pages/representatives/AssignRepresentative";
    page: "/co/representatives/manage";
  };
  "../pages/representatives/AcceptRepresentation.jsx": {
    id: "../pages/representatives/AcceptRepresentation";
    page: "/co/representatives/accept";
  };
  "../pages/search/index.jsx": {
    id: "../pages/search/index";
    page: "/search";
  };
  "../pages/service/service.jsx": {
    id: "../pages/service/service";
    page: "/services";
  };
  "../pages/service/serviceAdmin.jsx": {
    id: "../pages/service/serviceAdmin";
    page: "/services/add";
  };
  "../pages/service/serviceOverview.jsx": {
    id: "../pages/service/serviceOverview";
    page: "/services/:id";
  };
  "../pages/settings/index.jsx": {
    id: "../pages/settings/index";
    page: "/co/settings";
  };
  "../pages/feed/userProfile.jsx": {
    id: "../pages/feed/userProfile";
    page: "/co/:userId";
  };
  "../pages/authentication/AuthLayout.jsx": {
    id: "../pages/authentication/AuthLayout";
    page: "/signup" | "/login" | "/reactivate-account" | "/verify-account" | "/reset-password" | "/confirm-reset-password" | "/success";
  };
  "../pages/authentication/signup.jsx": {
    id: "../pages/authentication/signup";
    page: "/signup";
  };
  "../pages/authentication/login.jsx": {
    id: "../pages/authentication/login";
    page: "/login";
  };
  "../pages/authentication/reactivation.jsx": {
    id: "../pages/authentication/reactivation";
    page: "/reactivate-account";
  };
  "../pages/authentication/verify-account.jsx": {
    id: "../pages/authentication/verify-account";
    page: "/verify-account";
  };
  "../pages/authentication/reset-password.jsx": {
    id: "../pages/authentication/reset-password";
    page: "/reset-password";
  };
  "../pages/authentication/confirmPasswordReset.jsx": {
    id: "../pages/authentication/confirmPasswordReset";
    page: "/confirm-reset-password";
  };
  "../pages/authentication/successpage.jsx": {
    id: "../pages/authentication/successpage";
    page: "/success";
  };
  "../pages/terms&policies/termsLayout.jsx": {
    id: "../pages/terms&policies/termsLayout";
    page: "/terms-and-conditions" | "/privacy-policy";
  };
  "../pages/terms&policies/terms.jsx": {
    id: "../pages/terms&policies/terms";
    page: "/terms-and-conditions";
  };
  "../pages/terms&policies/policy.jsx": {
    id: "../pages/terms&policies/policy";
    page: "/privacy-policy";
  };
};